# ogólne
sonar.projectKey=T0siek_BudgetApp
sonar.organization=t0siek
sonar.host.url=https://sonarcloud.io

# backend
sonar.modules=backend,frontend

backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main/java
backend.sonar.java.binaries=target/classes

# frontend bez testów
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/*.test.tsx,**/_tests_/**